[ `uname -m` = x86_64 ] && apt-get install -y gcc-multilib

apt-get install -y \
autoconf \
automake \
autopoint \
autotools-dev \
bison \
bzip2 \
ccache \
cmake \
curl \
debhelper \
default-jdk \
default-jre \
doxygen \
fakeroot \
flex \
g++ \
gawk \
gcc \
gettext \
git \
gperf \
libao-dev \
libasound2-dev \
libass-dev \
libavahi-client-dev \
libavahi-common-dev \
libavcodec-dev \
libavfilter-dev \
libavformat-dev \
libavutil-dev \
libbluetooth-dev \
libbluray-dev \
libboost-dev \
libboost-thread-dev \
libbz2-dev \
libcap-dev \
libcec-dev \
libcrystalhd-dev \
libcurl4-openssl-dev \
libcwiid-dev \
libdbus-1-dev \
libenca-dev \
libflac-dev \
libfontconfig-dev \
libfreetype6-dev \
libfribidi-dev \
libgl1-mesa-dev \
libglew-dev \
libglib2.0-dev \
libglu-dev \
libglu1-mesa-dev \
libhal-dev \
libhal-storage-dev \
libiso9660-dev \
libjasper-dev \
libjpeg-dev \
libltdl-dev \
liblzo2-dev \
libmad0-dev \
libmicrohttpd-dev \
libmodplug-dev \
libmpcdec-dev \
libmpeg2-4-dev \
libmysqlclient-dev \
libncurses5-dev \
libnfs-dev \
libogg-dev \
libpcre3-dev \
libplist-dev \
libpng-dev \
libpng12-dev \
libpostproc-dev \
libpulse-dev \
libreadline-dev \
librtmp-dev \
libsamplerate-dev \
libsdl-dev \
libsdl-image1.2-dev \
libsdl-mixer1.2-dev \
libshairport-dev \
libsmbclient-dev \
libsqlite3-dev \
libssh-dev \
libssl-dev \
libswscale-dev \
libtaglib2.0-cil \
libtinyxml-dev \
libtool \
libudev-dev \
libusb-dev \
libva-dev \
libvdpau-dev \
libvorbis-dev \
libxinerama-dev \
libxmu-dev \
libxrandr-dev \
libxt-dev \
libyajl-dev \
lsb-release \
make \
openssh-server \
pkg-config \
python-dev \
python-support \
rpm \
ruby \
subversion \
swig \
texinfo \
unzip \
vim \
xfslibs-dev \
zip \
zlib1g-dev \

# libcdio-dev \
